/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Check API and database health */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get system brand and version info */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Gracefully shut down the server */
        post: operations["shutdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all registered CLI profiles */
        get: operations["listCliProfiles"];
        put?: never;
        /** @description Create a new CLI profile from a preset */
        post: operations["createCliProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli-profile/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a CLI profile by ID */
        get: operations["getCliProfile"];
        put?: never;
        post?: never;
        /** @description Delete a CLI profile by ID */
        delete: operations["deleteCliProfile"];
        options?: never;
        head?: never;
        /** @description Update an existing CLI profile */
        patch: operations["updateCliProfile"];
        trace?: never;
    };
    "/api/member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all registered members */
        get: operations["listMembers"];
        put?: never;
        /** @description Create a new member */
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/member/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a member by ID */
        get: operations["getMember"];
        put?: never;
        post?: never;
        /** @description Delete a member by ID */
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        /** @description Update an existing member */
        patch: operations["updateMember"];
        trace?: never;
    };
    "/api/sprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all sprints */
        get: operations["listSprints"];
        put?: never;
        /** @description Create and execute a new sprint */
        post: operations["createSprint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprint/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a sprint by ID */
        get: operations["getSprint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprint/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Stop a running sprint */
        post: operations["stopSprint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprint/{id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send a message to a sprint member */
        post: operations["sendSprintMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprint/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all messages addressed to the operator for a sprint */
        get: operations["getOperatorMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all system prompts */
        get: operations["listSystemPrompts"];
        put?: never;
        /** @description Create a new system prompt */
        post: operations["createSystemPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system-prompt/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a system prompt by ID */
        get: operations["getSystemPrompt"];
        put?: never;
        post?: never;
        /** @description Delete a system prompt by ID */
        delete: operations["deleteSystemPrompt"];
        options?: never;
        head?: never;
        /** @description Update an existing system prompt */
        patch: operations["updateSystemPrompt"];
        trace?: never;
    };
    "/api/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all environments */
        get: operations["listEnvironments"];
        put?: never;
        /** @description Create a new environment */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/env/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an environment by ID */
        get: operations["getEnvironment"];
        put?: never;
        post?: never;
        /** @description Delete an environment by ID */
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        /** @description Update an existing environment */
        patch: operations["updateEnvironment"];
        trace?: never;
    };
    "/api/git-repo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all git repos */
        get: operations["listGitRepos"];
        put?: never;
        /** @description Create a new git repo */
        post: operations["createGitRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git-repo/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a git repo by ID */
        get: operations["getGitRepo"];
        put?: never;
        post?: never;
        /** @description Delete a git repo by ID */
        delete: operations["deleteGitRepo"];
        options?: never;
        head?: never;
        /** @description Update an existing git repo */
        patch: operations["updateGitRepo"];
        trace?: never;
    };
    "/api/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all teams */
        get: operations["listTeams"];
        put?: never;
        /** @description Create a new team */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a team by ID */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        /** @description Delete a team by ID */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        /** @description Update an existing team */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/api/team/{id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the expanded structure of a team */
        get: operations["getTeamStructure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all members of a team */
        get: operations["listTeamMembers"];
        put?: never;
        /** @description Add a member to a team */
        post: operations["addTeamMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Remove a member from a team */
        delete: operations["removeTeamMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/{id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all relations of a team */
        get: operations["listTeamRelations"];
        put?: never;
        /** @description Add a relation between team members */
        post: operations["addTeamRelation"];
        /** @description Remove a relation between team members */
        delete: operations["removeTeamRelation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                    };
                };
            };
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        displayName: string;
                        binaryName: string;
                        configDir: string;
                        description: string;
                    };
                };
            };
        };
    };
    shutdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    listCliProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        model: string;
                        binary: "claude" | "codex";
                        systemArgs: string[];
                        customArgs: string[];
                        dotConfig: {
                            [key: string]: unknown;
                        };
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    createCliProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    preset: "claude-haiku" | "claude-sonnet" | "claude-opus" | "codex-5.4" | "codex-5.3" | "codex-mini";
                    customArgs?: string[];
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        model: string;
                        binary: "claude" | "codex";
                        systemArgs: string[];
                        customArgs: string[];
                        dotConfig: {
                            [key: string]: unknown;
                        };
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getCliProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        model: string;
                        binary: "claude" | "codex";
                        systemArgs: string[];
                        customArgs: string[];
                        dotConfig: {
                            [key: string]: unknown;
                        };
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    deleteCliProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CliProfile deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCliProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    customArgs?: string[];
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        model: string;
                        binary: "claude" | "codex";
                        systemArgs: string[];
                        customArgs: string[];
                        dotConfig: {
                            [key: string]: unknown;
                        };
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        cliProfileId: string;
                        systemPromptIds: string[];
                        environmentIds: string[];
                        gitRepoId: string | null;
                        cliProfileName: string;
                        systemPromptNames: string[];
                        environmentNames: string[];
                        gitRepoName: string | null;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    cliProfileId: string;
                    systemPromptIds?: string[];
                    environmentIds?: string[];
                    gitRepoId?: string | null;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        cliProfileId: string;
                        systemPromptIds: string[];
                        environmentIds: string[];
                        gitRepoId: string | null;
                        cliProfileName: string;
                        systemPromptNames: string[];
                        environmentNames: string[];
                        gitRepoName: string | null;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        cliProfileId: string;
                        systemPromptIds: string[];
                        environmentIds: string[];
                        gitRepoId: string | null;
                        cliProfileName: string;
                        systemPromptNames: string[];
                        environmentNames: string[];
                        gitRepoName: string | null;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    cliProfileId?: string;
                    systemPromptIds?: string[];
                    environmentIds?: string[];
                    gitRepoId?: string | null;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        cliProfileId: string;
                        systemPromptIds: string[];
                        environmentIds: string[];
                        gitRepoId: string | null;
                        cliProfileName: string;
                        systemPromptNames: string[];
                        environmentNames: string[];
                        gitRepoName: string | null;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    listSprints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        teamId: string;
                        teamSnapshot: {
                            teamName: string;
                            rootMemberId: string;
                            members: {
                                memberId: string;
                                memberName: string;
                                binary: "claude" | "codex";
                                model: string;
                                cliProfileName: string;
                                systemArgs: string[];
                                customArgs: string[];
                                dotConfig: {
                                    [key: string]: unknown;
                                };
                                systemPrompts: {
                                    name: string;
                                    prompt: string;
                                }[];
                                environments: {
                                    name: string;
                                    key: string;
                                    value: string;
                                }[];
                                gitRepo: {
                                    name: string;
                                    url: string;
                                } | null;
                                relations: {
                                    leaders: string[];
                                    workers: string[];
                                    peers: string[];
                                };
                                composedPrompt: string;
                            }[];
                        };
                        name: string;
                        state: "running" | "completed" | "errored";
                        error: string | null;
                        teamName: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    createSprint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    teamId: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        teamId: string;
                        teamSnapshot: {
                            teamName: string;
                            rootMemberId: string;
                            members: {
                                memberId: string;
                                memberName: string;
                                binary: "claude" | "codex";
                                model: string;
                                cliProfileName: string;
                                systemArgs: string[];
                                customArgs: string[];
                                dotConfig: {
                                    [key: string]: unknown;
                                };
                                systemPrompts: {
                                    name: string;
                                    prompt: string;
                                }[];
                                environments: {
                                    name: string;
                                    key: string;
                                    value: string;
                                }[];
                                gitRepo: {
                                    name: string;
                                    url: string;
                                } | null;
                                relations: {
                                    leaders: string[];
                                    workers: string[];
                                    peers: string[];
                                };
                                composedPrompt: string;
                            }[];
                        };
                        name: string;
                        state: "running" | "completed" | "errored";
                        error: string | null;
                        teamName: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        teamId: string;
                        teamSnapshot: {
                            teamName: string;
                            rootMemberId: string;
                            members: {
                                memberId: string;
                                memberName: string;
                                binary: "claude" | "codex";
                                model: string;
                                cliProfileName: string;
                                systemArgs: string[];
                                customArgs: string[];
                                dotConfig: {
                                    [key: string]: unknown;
                                };
                                systemPrompts: {
                                    name: string;
                                    prompt: string;
                                }[];
                                environments: {
                                    name: string;
                                    key: string;
                                    value: string;
                                }[];
                                gitRepo: {
                                    name: string;
                                    url: string;
                                } | null;
                                relations: {
                                    leaders: string[];
                                    workers: string[];
                                    peers: string[];
                                };
                                composedPrompt: string;
                            }[];
                        };
                        name: string;
                        state: "running" | "completed" | "errored";
                        error: string | null;
                        teamName: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    stopSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sprint stopped successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendSprintMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    from: string;
                    to: string;
                    content: string;
                };
            };
        };
        responses: {
            /** @description Message sent successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOperatorMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        fromMemberId: string;
                        toMemberId: string;
                        fromName: string;
                        toName: string;
                        content: string;
                        /** Format: date-time */
                        timestamp: string;
                    }[];
                };
            };
        };
    };
    listSystemPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        prompt: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    createSystemPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    prompt: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        prompt: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getSystemPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        prompt: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    deleteSystemPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SystemPrompt deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSystemPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    prompt?: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        prompt: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        key: string;
                        value: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    key: string;
                    value: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        key: string;
                        value: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        key: string;
                        value: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    key?: string;
                    value?: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        key: string;
                        value: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    listGitRepos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        url: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    createGitRepo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    url: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        url: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getGitRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        url: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    deleteGitRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitRepo deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateGitRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    url?: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        url: string;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        rootMemberId: string;
                        memberIds: string[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                        rootMemberName: string;
                        memberNames: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uuid */
                    rootMemberId: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        rootMemberId: string;
                        memberIds: string[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                        rootMemberName: string;
                        memberNames: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        rootMemberId: string;
                        memberIds: string[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                        rootMemberName: string;
                        memberNames: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** Format: uuid */
                    rootMemberId?: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        rootMemberId: string;
                        memberIds: string[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                        rootMemberName: string;
                        memberNames: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getTeamStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        rootMemberId: string;
                        members: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** Format: uuid */
                            cliProfileId: string;
                            systemPromptIds: string[];
                            environmentIds: string[];
                            gitRepoId: string | null;
                            cliProfileName: string;
                            systemPromptNames: string[];
                            environmentNames: string[];
                            gitRepoName: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                    };
                };
            };
        };
    };
    listTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        cliProfileId: string;
                        systemPromptIds: string[];
                        environmentIds: string[];
                        gitRepoId: string | null;
                        cliProfileName: string;
                        systemPromptNames: string[];
                        environmentNames: string[];
                        gitRepoName: string | null;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    addTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    memberId: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        rootMemberId: string;
                        memberIds: string[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                        rootMemberName: string;
                        memberNames: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    removeTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        rootMemberId: string;
                        memberIds: string[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                        rootMemberName: string;
                        memberNames: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    listTeamRelations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        from: string;
                        /** Format: uuid */
                        to: string;
                        type: "leader" | "peer";
                    }[];
                };
            };
        };
    };
    addTeamRelation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    from: string;
                    /** Format: uuid */
                    to: string;
                    /** @enum {string} */
                    type: "leader" | "peer";
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        rootMemberId: string;
                        memberIds: string[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                        rootMemberName: string;
                        memberNames: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
    removeTeamRelation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    from: string;
                    /** Format: uuid */
                    to: string;
                    /** @enum {string} */
                    type: "leader" | "peer";
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        /** Format: uuid */
                        rootMemberId: string;
                        memberIds: string[];
                        relations: {
                            /** Format: uuid */
                            from: string;
                            /** Format: uuid */
                            to: string;
                            type: "leader" | "peer";
                        }[];
                        rootMemberName: string;
                        memberNames: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
        };
    };
}
